microfin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    
    path('payment',include('payment.urls')),
]

payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('payment',views.payment,name='payment'),
    path('payment-status', views.payment_status, name='payment-status'),


 
    
]

user/urls.py
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index,name="index"),
    path('contact',views.contact,name='contact'),
    path('register',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('login2',views.login2,name='login2'),
    path('user_logout',views.user_logout,name='user_logout'),
    path('account_dashboard/',views.account_dashboard,name='account_dashboard'),
    path('customer_dashboardtable/',views.customer_dashboardtable,name='customer_dashboardtable'),
    
    # path('emicomplete',views.emicomplete,name='emicomplete'),
    path('password',views.change_password,name="password"),
    path('profile/',views.profile, name='profile'),
    path('chat',views.chat,name='chat'),
    path('allchat',views.allchat,name='allchat'),
    path('chatupdate/<int:todo_id>',views.chatupdate,name="chatupdate"),
    path('mychat',views.chatuserview,name='mychat'),
    
    path('paymentview',views.paymentview,name='paymentview'),
    
    path('create_account',views.create_account,name="create_account"),
    path('amount_transfer/<int:receiver_account_id>',views.amount_transfer,name="amount_transfer"),
    
    path('history',views.history,name="history"),
    path('add_reminder',views.add_reminder,name="add_reminder"),
    path('view_reminder',views.view_reminder,name="view_reminder"),
    path('view_my_accounts',views.view_my_accounts,name='view_my_accounts'),
    path('view_reciever_accounts/<int:account_id>',views.view_reciever_accounts,name='view_reciever_accounts'),


    path('reports',views.reports,name='reports'),
    path('transaction_report',views.transaction_report,name='transaction_report'),
    path('reminder_report',views.reminder_report,name='reminder_report'),
    path('complaint_report',views.complaint_report,name='complaint_report'),
    path('payment_report',views.payment_report,name='payment_report'),
    path('registration_report',views.registration_report,name='registration_report'),

    path('locations',views.locations,name='locations'),


    

    
    



    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/account_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>R&S - MICROFIN | Account</title>
    <!-- Core CSS - Include with every page -->
    <link href="/static/assets/plugins/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/static/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="/static/assets/css/style.css" rel="stylesheet" />
    <link href="/static/assets/css/main-style.css" rel="stylesheet" />
    <!-- Page-Level CSS -->
    <link href="/static/ssets/plugins/morris/morris-0.4.3.min.css" rel="stylesheet" />
   </head>
<body>
    <!--  wrapper -->
    <div id="wrapper">
        <!-- navbar top -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
            <!-- navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">
                    <!-- <img src="/static/assets/img/logo.png" alt="" /> -->
                </a>
            </div>
            <!-- end navbar-header -->
            <!-- navbar-top-links -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- main dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <!-- <span class="top-label label label-danger">3</span><i class="fa fa-envelope fa-3x"></i> -->
                    </a>
                    <!-- dropdown-messages -->
                    
                    <!-- end dropdown-messages -->
                </li>

                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <!-- <span class="top-label label label-warning">5</span>  <i class="fa fa-bell fa-3x"></i> -->
                    </a>
                    <!-- dropdown alerts-->
                    <!-- end dropdown-alerts -->
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-3x"></i>
                    </a>
                    <!-- dropdown user-->
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'profile' %}"><i class="fa fa-user fa-fw"></i>User Profile</a>
                        </li>
                        <li><a href="{% url 'password' %}"><i class="fa fa-gear fa-fw"></i>Settings</a>
                        </li>
                        <li class="divider"></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'user_logout' %}"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- end dropdown-user -->
                </li>
                <!-- end main dropdown -->
            </ul>
            <!-- end navbar-top-links -->

        </nav>
        <!-- end navbar top -->
{% include 'sidebar1.html' %}
        <!-- navbar side -->
  
        <!-- end navbar side -->
        <!--  page-wrapper -->
        {% block content %}
        <div id="page-wrapper">

            <div class="row">
                <!-- Page Header -->
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!--End Page Header -->
            </div>
            
    
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   
        <br>
        


   
    {% for i in curr_user %}
    <div class="card-deck col-lg-4 col-md-3" >
    
       
        <div class="card" style="background-color: #ff5959;padding:2em;height: 28em;">
          
          <div class="card-body">
            <h5 class="card-title" style="font-size: 1.5em;font-weight: bold;">BANK NAME:<span style="color: white;font-size: 1.6em;"> {{i.bank.bankname}}</span></h5>
            <h5 class="card-title" style="font-size: 1.3em;font-weight: bold;">BANK HOLDER NAME: <span style="color: white;font-size: 1.4em;">{{i.user.username}}</span></h5>
            <h5 class="card-title" style="font-size: 1.3em;font-weight: bold;">ACCOUNT NUMBER:<span style="color: white;font-size: 1.4em;"> {{i.account_no}}</span></h5>
            <h5 class="card-title" style="font-size: 1.3em;font-weight: bold;">AMOUNT: <span style="color: white;font-size: 1.4em;">{{i.balance}}.rs</span></h5>
            
            
          </div>
        </div>
    </div>
        
      {% endfor %}
    




       
      
        
  


{% endblock %}
                
    <!-- Core Scripts - Include with every page -->
    <script src="/static/assets/plugins/jquery-1.10.2.js"></script>
    <script src="/static/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="/static/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/assets/plugins/pace/pace.js"></script>
    
    <!-- Page-Level Plugin Scripts-->
    <script src="/static/assets/plugins/morris/raphael-2.1.0.min.js"></script>
    <script src="/static/assets/plugins/morris/morris.js"></script>
    <script src="/static/assets/scripts/dashboard-demo.js"></script>
    
</body>

</html>

templates/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="zxx">

<head>
    <title>Promote Business Category Bootstrap Responsive Web Template | Home :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content="Promote Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- //Meta tag Keywords -->

    <!-- Custom-Files -->
    <link rel="stylesheet" href="static/css/bootstrap.css">
    <!-- Bootstrap-Core-CSS -->
    <link rel="stylesheet" href="static/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="static/css/login.css" type="text/css" media="all" />
	  <link rel="stylesheet" href="static/css/slider.css" type="text/css" media="all" />
    <!-- Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="static/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
   <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
   <!-- header -->
<header>
	<div class="container">
		<!-- nav -->
		<nav class="py-3 d-lg-flex">
			<div id="logo">
				<h1> <a href="index.html"><span class="fa fa-rocket"></span> Promote </a></h1>
			</div>
			<label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
			<input type="checkbox" id="drop" />
			<ul class="menu ml-auto mt-1">
				<li class="active"><a href="{% url 'index' %}">Home</a></li>
				<li class=""><a href="#about">About Us</a></li>
				<li class=""><a href="#services">Services</a></li>
				<li class=""><a href="#portfolio">Portfolio</a></li>
				<li class=""><a href="#contact">Contact</a></li>
				 {% if user.is_authenticated %} 
				{% if user.is_superuser %}
				 <li><a href="{% url 'admin:index' %}">Admin</a></li>
                 {% endif %}
                 {% if user.register.user_type == 'manager' %}
				  <li><a href="{% url 'account_dashboard' %}">Manager</a></li>
				 {% endif %}
                 {% if user.register.user_type == 'customer' %}
				  <li><a href="{% url 'account_dashboard' %}">Customer</a></li>
				 {% endif %}
                 <li><a href="{% url 'user_logout' %}">Logout</a></li>
                  {% else %}
				
				<li class="last-grid"><a href="#register">Register now</a></li>
				<li><a href="{% url 'user_login' %}">Login</a></li>
				{% endif %}
				
			</ul>
		</nav>
		<!-- //nav -->
	</div>
</header>
<!-- //header -->


<!-- banner -->
<div class="banner" id="home">
	<div class="layer">
		<div class="container">
			<div class="banner-text-w3pvt">
				<!-- banner slider-->
				<div class="static/csslider infinity" id="slider1">
					{% comment %} <input type="radio" name="slides" id="slides_2" />
					<input type="radio" name="slides" id="slides_3" /> {% endcomment %}
					<ul class="banner_slide_bg">
						{% comment %} <li> {% endcomment %}
							<div class="w3ls_banner_txt">
				
						
					
							</div>
						</li>
						{% comment %} <li> {% endcomment %}
							<div class="w3ls_banner_txt">
                        

	<div class="form-box">
		<div class="header-text">
			<!-- <h1 style="color:crimson;">Login Form</h1> -->
    <form action="" method="POST">
    {% csrf_token %}
		</div><input placeholder="User Name"  name='username' type="text" required> <input placeholder="Your Password" name='password' type="password" required> <button>login</button>
	</form>
    </div>


				
								
								
								
							</div>
						</li>
						<li>
							<div class="w3ls_banner_txt">
						
								
						
								
							</div>
						</li>
					</ul>
					<div class="navigation">
						<div>
							<label for="slides_1"></label>
							<label for="slides_2"></label>
							<label for="slides_3"></label>
						</div>
					</div>
				</div>
				<!-- //banner slider-->
			</div>
		</div>
	</div>
</div>

<!-- footer -->
<footer class="py-md-5 py-3">
	<div class="container py-md-5 py-3">
		<div class="row footer-grids">
			<div class="col-lg-3 col-sm-6 mb-lg-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Promote</h4>
				<p class="mb-3">Onec Consequat sapien ut cursus rhoncus. Nullam dui mi, vulputate ac metus semper quis luctus sed.</p>
				
			</div>
			<div class="col-lg-3 col-sm-6 mb-md-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Address Info</h4>
				<p><span class="fa mr-2 fa-map-marker"></span>6d canal street TT 3356 <span>Newyork.</span></p>
				<p class="phone py-2"><span class="fa mr-2 fa-phone"></span> +1(12) 123 456 789 </p>
				<p><span class="fa mr-2 fa-envelope"></span><a href="mailto:info@example.com">info@example.com</a></p>
			</div>
			<div class="col-lg-2 col-sm-6 mb-lg-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Quick Links</h4>
				<ul>
					<li><a href="#register">Register here </a></li>
					<li class="my-2"><a href="#team">Business Team</a></li>
					<li><a href="#contact">Support Helpline</a></li>
					<li class="mt-2"><a href="#">Privacy Policy</a></li>
				</ul>
			</div>
			<div class="col-lg-4 col-sm-6">
				<h4 class="mb-4">Subscribe Us</h4>
				<p class="mb-3">Subscribe to our newsletter</p>
				<form action="#" method="post" class="d-flex">
					<input type="email" id="email" name="EMAIL" placeholder="Enter your email here" required="">
					<button type="submit" class="btn">Subscribe</button>
				</form>
			</div>
		</div>
	</div>
</footer>
<!-- //footer -->

<!-- copyright -->
<div class="copyright">
	<div class="container py-4">
		<div class=" text-center">
			<p>© 2019 promote. All Rights Reserved | Design by <a href="http://w3layouts.com/"> W3layouts</a> </p>
		</div>
	</div>
</div>
<!-- //copyright -->
		
<!-- move top -->
<div class="move-top text-right">
	<a href="#home" class="move-top"> 
		<span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
	</a>
</div>
<!-- move top -->



</body>
</html>

templates/login2.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="zxx">

<head>
    <title>Promote Business Category Bootstrap Responsive Web Template | Home :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content="Promote Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- //Meta tag Keywords -->

    <!-- Custom-Files -->
    <link rel="stylesheet" href="static/css/bootstrap.css">
    <!-- Bootstrap-Core-CSS -->
    <link rel="stylesheet" href="static/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="static/css/login.css" type="text/css" media="all" />
	  <link rel="stylesheet" href="static/css/slider.css" type="text/css" media="all" />
    <!-- Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="static/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
   <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
   <!-- header -->
<header>
	<div class="container">
		<!-- nav -->
		<nav class="py-3 d-lg-flex">
			<div id="logo">
				<h1> <a href="index.html"><span class="fa fa-rocket"></span> Promote </a></h1>
			</div>
			<label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
			<input type="checkbox" id="drop" />
			<ul class="menu ml-auto mt-1">
				<li class="active"><a href="{% url 'index' %}">Home</a></li>
				<li class=""><a href="#about">About Us</a></li>
				<li class=""><a href="#services">Services</a></li>
				<li class=""><a href="#portfolio">Portfolio</a></li>
				<li class=""><a href="#contact">Contact</a></li>
				 {% if user.is_authenticated %} 
				{% if user.is_superuser %}
				 <li><a href="{% url 'admin:index' %}">Admin</a></li>
                 {% endif %}
                 {% if user.register.user_type == 'manager' %}
				  <li><a href="{% url 'account_dashboard' %}">Manager</a></li>
				 {% endif %}
                 {% if user.register.user_type == 'customer' %}
				  <li><a href="{% url 'account_dashboard' %}">Customer</a></li>
				 {% endif %}
                 <li><a href="{% url 'user_logout' %}">Logout</a></li>
                  {% else %}
				
				<li class="last-grid"><a href="#register">Register now</a></li>
				<li><a href="{% url 'user_login' %}">Login</a></li>
				{% endif %}
				
			</ul>
		</nav>
		<!-- //nav -->
	</div>
</header>
<!-- //header -->


<!-- banner -->
<div class="banner" id="home">
	<div class="layer">
		<div class="container">
			<div class="banner-text-w3pvt">
				<!-- banner slider-->
				<div class="static/csslider infinity" id="slider1">
					{% comment %} <input type="radio" name="slides" id="slides_2" />
					<input type="radio" name="slides" id="slides_3" /> {% endcomment %}
					<ul class="banner_slide_bg">
						{% comment %} <li> {% endcomment %}
							<div class="w3ls_banner_txt">
				
						
					
							</div>
						</li>
						{% comment %} <li> {% endcomment %}
							<div class="w3ls_banner_txt">
                        

	<div class="form-box">
		<div class="header-text">
			<!-- <h1 style="color:crimson;">Login Form</h1> -->
    <form action="" method="POST">
    {% csrf_token %}
		</div><input placeholder="UPI"  name='upi' type="text" required> <button>login</button>
	</form>
    </div>


				
								
								
								
							</div>
						</li>
						<li>
							<div class="w3ls_banner_txt">
						
								
						
								
							</div>
						</li>
					</ul>
					<div class="navigation">
						<div>
							<label for="slides_1"></label>
							<label for="slides_2"></label>
							<label for="slides_3"></label>
						</div>
					</div>
				</div>
				<!-- //banner slider-->
			</div>
		</div>
	</div>
</div>

<!-- footer -->
<footer class="py-md-5 py-3">
	<div class="container py-md-5 py-3">
		<div class="row footer-grids">
			<div class="col-lg-3 col-sm-6 mb-lg-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Promote</h4>
				<p class="mb-3">Onec Consequat sapien ut cursus rhoncus. Nullam dui mi, vulputate ac metus semper quis luctus sed.</p>
				
			</div>
			<div class="col-lg-3 col-sm-6 mb-md-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Address Info</h4>
				<p><span class="fa mr-2 fa-map-marker"></span>6d canal street TT 3356 <span>Newyork.</span></p>
				<p class="phone py-2"><span class="fa mr-2 fa-phone"></span> +1(12) 123 456 789 </p>
				<p><span class="fa mr-2 fa-envelope"></span><a href="mailto:info@example.com">info@example.com</a></p>
			</div>
			<div class="col-lg-2 col-sm-6 mb-lg-0 mb-sm-5 mb-4">
				<h4 class="mb-4">Quick Links</h4>
				<ul>
					<li><a href="#register">Register here </a></li>
					<li class="my-2"><a href="#team">Business Team</a></li>
					<li><a href="#contact">Support Helpline</a></li>
					<li class="mt-2"><a href="#">Privacy Policy</a></li>
				</ul>
			</div>
			<div class="col-lg-4 col-sm-6">
				<h4 class="mb-4">Subscribe Us</h4>
				<p class="mb-3">Subscribe to our newsletter</p>
				<form action="#" method="post" class="d-flex">
					<input type="email" id="email" name="EMAIL" placeholder="Enter your email here" required="">
					<button type="submit" class="btn">Subscribe</button>
				</form>
			</div>
		</div>
	</div>
</footer>
<!-- //footer -->

<!-- copyright -->
<div class="copyright">
	<div class="container py-4">
		<div class=" text-center">
			<p>© 2019 promote. All Rights Reserved | Design by <a href="http://w3layouts.com/"> W3layouts</a> </p>
		</div>
	</div>
</div>
<!-- //copyright -->
		
<!-- move top -->
<div class="move-top text-right">
	<a href="#home" class="move-top"> 
		<span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
	</a>
</div>
<!-- move top -->



</body>
</html>

templates/sidebar1.html
<html>
<title>nav</title>
<body>
    <link href="/static/assets/plugins/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/static/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="/static/assets/css/style.css" rel="stylesheet" />
    <link href="/static/assets/css/main-style.css" rel="stylesheet" />
    <!-- Page-Level CSS -->
    <link href="/static/ssets/plugins/morris/morris-0.4.3.min.css" rel="stylesheet" />

      <nav class="navbar-default navbar-static-side" role="navigation">
            <!-- sidebar-collapse -->
            <div class="sidebar-collapse">
                <!-- side-menu -->
                <ul class="nav" id="side-menu">
                    <li>
                        <!-- user image section-->
                        <div class="user-section">
                            <div class="user-section-inner">
                                
                                <img src="{{user.register.image.url}}" alt="">
                                

                            </div>
                            <div class="user-info">
                                <div>{{user.first_name}} <strong>{{user.last_name}}</strong></div>
                                <div class="user-text-online">
                                    <span class="user-circle-online btn btn-success btn-circle "></span>&nbsp;Online
                                </div>
                            </div>
                        </div>
                        <!--end user image section-->
                    </li>
                    
                    <li class="selected">
                        <a href="{% url 'index' %}"><i class="fa fa-dashboard fa-fw"></i>Home</a>
                    </li>

                    <li class="selected">
                        <a href="{% url 'create_account' %}"><i class="fa fa-dashboard fa-fw"></i>Create Account</a>
                    </li>
                    
                    <li class="selected">
                        <a href="{% url 'account_dashboard' %}"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
                    </li>
                
                    <li>
                        <a href="{% url 'view_my_accounts' %}"><i class="fa fa-edit fa-fw"></i>Money Transfer</a>
                    </li>

                    <li>
                        <a href="{% url 'history' %}"><i class="fa fa-edit fa-fw"></i>Money Transfer History</a>
                    </li>
                    
                    <li>
                        <a href="{% url 'payment:payment' %}"><i class="fa fa-edit fa-fw"></i>Payment</a>
                    </li>
                    {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'admin:index' %}"><i class="fa fa-edit fa-fw"></i>Admin </a>
                    </li>
                    <li>
                        <a href="{% url 'locations' %}"><i class="fa fa-edit fa-fw"></i>LOCATIONS</a>
                    </li>
                   
                    {% endif %}
                    
                    {% if user.register.user_type == 'customer' %}
                    <li class="selected">
                        <a href="{% url 'chat' %}"><i class="fa fa-dashboard fa-fw"></i>Complaint</a>
                    </li>
                    <li class="selected">
                        <a href="{% url 'mychat' %}"><i class="fa fa-dashboard fa-fw"></i>Complaint Status</a>
                    </li>
                    <li class="selected">
                        <a href="{% url 'paymentview' %}"><i class="fa fa-dashboard fa-fw"></i>Payment View</a>
                    </li>

                    <li class="selected">
                        <a href="{% url 'add_reminder' %}"><i class="fa fa-dashboard fa-fw"></i>Add Reminder</a>
                    </li>


                    <li class="selected">
                        <a href="{% url 'view_reminder' %}"><i class="fa fa-dashboard fa-fw"></i>View My Reminder</a>
                    </li>
                    
                    
                    

                   
                {% endif %}    
                <li class="selected">
                    <a href="{% url 'reports' %}"><i class="fa fa-dashboard fa-fw"></i>REPORTS</a>
                </li>    
                        <!-- second-level-items -->
                    
                   
                <!-- end side-menu -->
            </div>
            <!-- end sidebar-collapse -->
        </nav>
        <script src="static/assets/plugins/jquery-1.10.2.js"></script>
        <script src="static/assets/plugins/bootstrap/bootstrap.min.js"></script>
        <script src="/static/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="/static/assets/plugins/pace/pace.js"></script>
        
        <!-- Page-Level Plugin Scripts-->
        <script src="static/assets/plugins/morris/raphael-2.1.0.min.js"></script>
        <script src="static/assets/plugins/morris/morris.js"></script>
        <script src="static/assets/scripts/dashboard-demo.js"></script>
        </body>
        </html>